# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty 
permalink:       /:title

# Setup
title:            MTBlog
tagline:          "Marcus' Technology Blog"
description:      'Blog posts about programming, Linux, prototyping and much more.'
url:              http://mirtio.github.io
baseurl:          'https://mirtio.github.io/'
paginate:         5

author:
  name:           'Marcus Sonntag'
  url:            https://twitter.com/dimso

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mirtio/mirtio.github.io
  