# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty 
permalink:       /:title

# Setup
title:            MTBlog
tagline:          "Marcus' Technology Blog"
description:      'Blog posts about programming, Linux, prototyping and much more.'
keywords:         
   - programming 
   - linux 
   - android 
   - rapid prototyping 
   - matlab 
   - simulink 
   - engineering 
   - microcontroller 
   - PCB 
   - 3d printing
url:              http://sonntam.github.io
baseurl:          'https://sonntam.github.io/'
paginate:         5
# Exclude .bak files from text editors
exclude:        
   - Gemfile
   - Gemfile.lock
   - "*.bak"
   - "_drafts/*.bak"
   - "_posts/*.bak"
   - servesite.bat

author:
  name:           'Marcus Sonntag'
  url:            https://twitter.com/dimso

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/sonntam/sonntam.github.io
  
